<?php $url_order = ($this->order == 'ASC') ? 'DESC' : 'ASC'; ?>

<?php
	$buscarForm = $this->buscarForm;
	$buscarForm->setAttribute('action', $this->url('area-conocimiento'));
	$buscarForm->prepare();
?>

<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-graduation-cap"></i>
		<h3>Areas del Conocimiento</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">
	
		<div class="row">
		
			<div class="col-lg-6 col-md-6 col-sm-4 col-xs-12 margin-bottom">
				<a class="btn btn-labeled btn-success" href="<?php echo $this->url("area-conocimiento", array('action' => 'agregar-area-conocimiento')); ?>"><span class="btn-label"><i class="fa fa-fw fa-plus-square"></i></span>Agregar</a>
			</div>
			
			<div class="col-lg-6 col-md-6 col-sm-8 col-xs-12 margin-bottom">
				<?php echo $this->form()->openTag($buscarForm);?>
					<div class="input-group">						
						<?php echo $this->formInput($buscarForm->get('texto')); ?>
						<span class="input-group-btn">
							<?php echo $this->formInput($buscarForm->get('buscar')); ?>
						</span>
					</div>
				<?php echo $this->form()->closeTag($buscarForm);?>
			</div>
			
		</div>
				
		<hr>
		
						<?php
                            if ($this->messages):
                                foreach ($this->messages as $msg):
                                    ?>
                                    <div class="alert alert-error alert-dismissable bg-success">                                        
                                        <?php echo $msg; ?>
                                    </div>
                                <?php
                                endforeach;
                            endif;
                       	?>	
		
		<?php if($this->areasConocimiento->count() != 0):?>
			<table class="table table-hover table-striped" data-server="cp">
			    <thead>
			    <tr>
			        <th><a href="<?php echo $this->url('area-conocimiento', array('action' => 'index', 'orderby' => 'codareaconocimiento', 'order' => $url_order)); ?>">Código <?php if ($this->orderby == 'codareaconocimiento'): ?><i class="glyphicon glyphicon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
			        <th><a href="<?php echo $this->url('area-conocimiento', array('action' => 'index', 'orderby' => 'areaconocimiento', 'order' => $url_order)); ?>">Area del Conocimiento <?php if ($this->orderby == 'areaconocimiento'): ?><i class="glyphicon glyphicon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
			        <th>Acciones</th>
			    </tr>
			    </thead>
			    <tbody>
			    <?php foreach ($this->areasConocimiento as $areaConocimiento) : ?>    
			    <tr>        
			        <td><?php echo $this->escapeHtml($areaConocimiento['codAreaConocimiento']);?></td>			    
			        
			        <td><?php echo $this->escapeHtml($areaConocimiento['areaConocimiento']);?></td>		        
			        
			        <td>
						<a title="Editar Area del Conocimiento" class="btn btn-info btn-sm" href="<?php echo $this->url('area-conocimiento', array('action' => 'editar-area-conocimiento','codareaconocimiento' => $areaConocimiento['codAreaConocimiento']));?>" >
							<i class="fa fa-edit"></i>  
						</a>
						<a title="Eliminar Area del Conocimiento" class="btn btn-danger btn-sm" href="<?php echo $this->url('area-conocimiento', array('action' => 'eliminar-area-conocimiento', 'codareaconocimiento' => $areaConocimiento['codAreaConocimiento']));?>">
							<i class="fa fa-trash-o "></i> 
						</a>
					</td>
			    </tr>
			    <?php endforeach; ?>
			    </tbody>
			    <tfoot>
			    <tr>
			        <th>Código</th>
			        <th>Area del Conocimiento</th>
			        <th>Acciones</th>
			    </tr>
			    </tfoot>    
			</table>

			<?php echo $this->paginationControl($this->areasConocimiento, 'Sliding', 'paginator', array('route' => 'area-conocimiento', 'action' => 'index', 'orderby' => $this->orderby, 'order' => $order));?>

			<?php else: ?>
			
			<h2>No se han encontrado resultados.</h2>
		
		<?php endif;?>			
	</div>
</div>
