
<section>

    <div class="custom-box palette-asbestos">
		<p>El presente reporte permite visualizar el avance de sílabo, los filtros que puede usar son: </p>
		<ol>
			<li>Es Común: <em>Es opcional y especifica si el curso es común.</em></li>
			<li>Area del Conocimiento: <em>Es opcional y dependerá si ha seleccionado común o no.</em></li>
			<li>Carrera Profesional: <em>Es opcional y dependerá si ha seleccionado común o no.</em></li>
			<li>Ciclo Acádemico: <em>Es opcional, usarlo si se requiere.</em></li>
			<li>Docente: <em>Es obligatorio, si se deja en blanco no traerá ningún resultado.</em></li>
		</ol>
	</div>
    
    <hr>     

    <div class="row">
	    <?php
	        $form = $this->form;        
	        $form->setAttribute('action', $this->url('reportes', array('action' => 'primer-reporte')));
	        $form->prepare();        
	    ?>
    
    	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 margin-bottom">    
		    <?php echo $this->form()->openTag($form); ?>
		    
			    <div class="form-group">
					<?php echo $this->formSelect($form->get('esComun'));?>
					<span><?php echo $this->formElementErrors($form->get('esComun'));?></span>
				</div>
			    
			    <div class="form-group">
					<?php echo $this->formSelect($form->get('codAreaConocimiento'));?>
					<span><?php echo $this->formElementErrors($form->get('codAreaConocimiento'));?></span>
				</div>
			    
			    <div class="form-group">
					<?php echo $this->formSelect($form->get('codCarreraProfesional'));?>
					<span><?php echo $this->formElementErrors($form->get('codCarreraProfesional'));?></span>
				</div>
				
				<div class="form-group">
					<?php echo $this->formSelect($form->get('codCicloAcademico'));?>
					<span><?php echo $this->formElementErrors($form->get('codCicloAcademico'));?></span>
				</div>
				
				<div class="form-group">
					<!-- <label for="codDocente"><?php //echo $this->formLabel($form->get('codDocente')); ?></label> -->
					<?php echo $this->formSelect($form->get('codDocente'));?>
					<span><?php echo $this->formElementErrors($form->get('codDocente'));?></span>
				</div>
			    
			    <?php echo $this->formSubmit($form->get('listar'));?>
		    
		    <?php echo $this->form()->closeTag() ?>
		</div>

    </div>	
    <hr>
</section>

<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-cube"></i>
		<h3>Cursos</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">			
		
		<?php if($this->cursos != null):?>
			<table class="table">
			    <thead>
			    <tr>
			        <th>N°</th>			        
			        <th>Es Común</th>
			        <th>Area del Conocimiento</th>
			        <th>Carrera Profesional</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Paralelo</th>
			        <th>Aula</th>
			        <th>Sección</th>
			        <th>Total de temas</th>
			        <th>Temas terminados</th>
			        <th>% Avanzado</th>			        
			    </tr>
			    </thead>
			    <tbody>
			    <?php
			    	$i = 0;
					foreach ($this->cursos as $curso) :
					$i++;
				?>    
			    <tr>
			        <td><?php echo $i;?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['esComun']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['areaConocimiento']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['carreraProfesional']);?></td>       
			        
			        <td><?php echo $this->escapeHtml($curso['codigo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['curso']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['modalidad']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['paralelo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['numero']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['seccion']);?></td>			        
			        
			        <td><?php echo ($curso['totalTemas']) ? $curso['totalTemas'] : "0"; ?></td>
			        
			        <td><?php echo $curso['totalTemasTerminados'] ? $curso['totalTemasTerminados'] : "0";?></td>       			        
			        
			        <?php
			        
			        	$barra = "_red";
			        	$porcentajeAvance = 0;
			        	
			        	if($curso['totalTemas'] != 0 )
			        	{
				        	$porcentajeAvance = round($curso['totalTemasTerminados'] * 100 /  $curso['totalTemas'], 2);			        	
				        	
				        	if($porcentajeAvance >= 70 && $porcentajeAvance <= 85) $barra = "_yellow";
				        	if($porcentajeAvance > 85) $barra = "_green";
			        	}
			        ?>
			        
			        <td><div class="grafico grafico<?php echo $barra;?>"><strong class="barra barra<?php echo $barra;?>" style="width: <?php echo $porcentajeAvance; ?>%;"><?php echo $porcentajeAvance; ?>%</strong></div></td>		        		        
			        
			    </tr>
			    <?php endforeach; ?>
			    </tbody>
			    <tfoot>
			    <tr>
			        <th>N°</th>
			        <th>Es Común</th>
			        <th>Area del Conocimiento</th>
			        <th>Carrera Profesional</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Paralelo</th>
			        <th>Aula</th>
			        <th>Sección</th>
			        <th>Total de temas</th>
			        <th>Temas terminados</th>
			        <th>% Avanzado</th>	        
			    </tr>
			    </tfoot>    
			</table>
			<?php else: ?>
			
			<h2>No se han encontrado resultados</h2>
		
		<?php endif;?>			
	</div>
</div>