<?php
$title = "Top 10 cursos con mayor avance";
?>

<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-cube"></i>
		<h3><?php echo $title;?></h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	
	<div class="box-body">			
		
		<?php if($this->cursosMayor != null):?>
			<table class="table">
			    <thead>
			    <tr>
			        <th>N°</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Paralelo</th>
			        <th>Aula</th>
			        <th>Sección</th>        
			        <th>Docente</th>
			        <th>Total de temas</th>
			        <th>Temas terminados</th>
			        <th>% Avanzado</th>			        
			    </tr>
			    </thead>
			    <tbody>
			    <?php
			    	$i = 0;
					foreach ($this->cursosMayor as $curso) :
					$i++;
				?>    
			    <tr>
			        <td><?php echo $i;?></td>       
			        
			        <td><?php echo $this->escapeHtml($curso['codigo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['curso']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['modalidad']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['paralelo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['numero']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['seccion']);?></td>    
			        
			        <td><?php echo $this->escapeHtml($curso['nombres'] . ' ' . $curso['primerApellido'] . ' ' . $curso['segundoApellido']);?></td>    
			        
			        <td><?php echo ($curso['totalTemas']) ? $curso['totalTemas'] : "0"; ?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['maxTemasTerminados']);?></td>       			        
			        
			        <?php
			        
			        	$barra = "_red";
			        	$porcentajeAvance = 0;
			        	
			        	if($curso['totalTemas'] != 0 )
			        	{
				        	$porcentajeAvance = round($curso['avance'], 2); //round($curso['maxTemasTerminados'] * 100 /  $curso['totalTemas'], 2);			        	
				        	
				        	if($porcentajeAvance >= 70 && $porcentajeAvance <= 85) $barra = "_yellow";
				        	if($porcentajeAvance > 85) $barra = "_green";
			        	}
			        ?>
			        
			        <td><div class="grafico grafico<?php echo $barra;?>"><strong class="barra barra<?php echo $barra;?>" style="width: <?php echo $porcentajeAvance; ?>%;"><?php echo $porcentajeAvance; ?>%</strong></div></td>		        		        
			        
			    </tr>
			    <?php endforeach; ?>
			    </tbody>
			    <tfoot>
			    <tr>
			        <th>N°</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Paralelo</th>
			        <th>Aula</th>
			        <th>Sección</th>        
			        <th>Docente</th>
			        <th>Total de temas</th>
			        <th>Temas terminados</th>
			        <th>% Avanzado</th>			        
			    </tr>
			    </tfoot>    
			</table>
			<?php else: ?>
			
			<h2>No se han encontrado resultados</h2>
		
		<?php endif;?>			
	</div>
</div>



<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-cube"></i>
		<h3>Top 10 cursos con menor avance</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">			
		
		<?php if($this->cursosMenor != null):?>
			<table class="table">
			    <thead>
			    <tr>
			        <th>N°</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Paralelo</th>
			        <th>Aula</th>
			        <th>Sección</th>        
			        <th>Docente</th>
			        <th>Total de temas</th>
			        <th>Temas terminados</th>
			        <th>% Avanzado</th>			        
			    </tr>
			    </thead>
			    <tbody>
			    <?php
			    	$i = 0;
					foreach ($this->cursosMenor as $curso) :
					$i++;
				?>    
			    <tr>
			        <td><?php echo $i;?></td>       
			        
			        <td><?php echo $this->escapeHtml($curso['codigo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['curso']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['modalidad']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['paralelo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['numero']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['seccion']);?></td>    
			        
			        <td><?php echo $this->escapeHtml($curso['nombres'] . ' ' . $curso['primerApellido'] . ' ' . $curso['segundoApellido']);?></td>
			        
			        <td><?php echo ($curso['totalTemas']) ? $curso['totalTemas'] : "0"; ?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['maxTemasTerminados']);?></td>  			        
			        
			        <?php
			        
			        	$barra = "_red";
			        	$porcentajeAvance = 0;
			        	
			        	if($curso['totalTemas'] != 0 )
			        	{
				        	$porcentajeAvance = round($curso['avance'], 2);
				        	
				        	if($porcentajeAvance >= 70 && $porcentajeAvance <= 85) $barra = "_yellow";
				        	if($porcentajeAvance > 85) $barra = "_green";
			        	}
			        ?>
			        
			        <td><div class="grafico grafico<?php echo $barra;?>"><strong class="barra barra<?php echo $barra;?>" style="width: <?php echo $porcentajeAvance; ?>%;"><?php echo $porcentajeAvance; ?>%</strong></div></td>		        		        
			        
			    </tr>
			    <?php endforeach; ?>
			    </tbody>
			    <tfoot>
			    <tr>
			        <th>N°</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Paralelo</th>
			        <th>Aula</th>
			        <th>Sección</th>        
			        <th>Docente</th>
			        <th>Total de temas</th>
			        <th>Temas terminados</th>
			        <th>% Avanzado</th>			        
			    </tr>
			    </tfoot>    
			</table>
			<?php else: ?>
			
			<h2>No se han encontrado resultados</h2>
		
		<?php endif;?>			
	</div>
</div>