
<section>
	<div class="row"> 
	
	    <?php
	        $form = $this->form;        
	        $form->setAttribute('action', $this->url('reportes', array('action' => 'septimo-reporte')));
	        $form->prepare();	        
	    ?>
	
	    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 margin-bottom">	    
		    <?php echo $this->form()->openTag($form); ?>
		    
			    <div class="form-group">
					<?php echo $this->formSelect($form->get('codDocente'));?>
					<span><?php echo $this->formElementErrors($form->get('codDocente'));?></span>
				</div>
			    
			    <?php echo $this->formSubmit($form->get('listar'));?>
		    
		    <?php echo $this->form()->closeTag() ?>	
	    </div>
	    
	</div>

</section>


<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-cube"></i>
		<h3>Docentes</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">			
		
		<?php if($this->docentes != null):?>
			<table class="table table-hover">
			    <thead>
			    <tr>			        
			       	<th>N°</th>
			        <th>Docente</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Paralelo</th>
			        <th>Aula</th>
			        <th>Sección</th>
			        <th>Asistencias</th>
			        <th>&nbsp;</th>     
				</tr>
			    </thead>
			    <tbody>
			    <?php
			    	$i = 0;
					foreach ($this->docentes as $curso) :
					$i++;
				?>    
			    <tr class="fila" id="<?php echo $i;?>" style="cursor: pointer;">
			    
			        <td><?php echo $i;?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['nombres'] . ' ' . $curso['primerApellido'] . ' ' . $curso['segundoApellido']);?></td>   
			        
			        <td><?php echo $this->escapeHtml($curso['codigo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['curso']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['modalidad']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['paralelo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['numero']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['seccion']);?></td>     
			        
			        <td><?php echo ($curso['asistencias']) ? $curso['asistencias'] : "0"; ?></td>
			        		        			        
			        <td><a class="btn btn-labeled btn-danger" target="_blank" href="<?php echo $this->url("reportes", array(
																									'action' => 'septimo-reporte-pdf',
																									'imprimirpdf' => 'si',
																									'codcicloacademico'=> $curso['codCicloAcademico'],
																									'codcurso'=> $curso['codCurso'],
																									'codmodalidad'=> $curso['codModalidad'],
																									'paralelo'=> $curso['paralelo'],
																					        		'codaula'=> $curso['codAula'],
																					        		'codseccion'=> $curso['codSeccion'],
																					        		'coddocente'=> $curso['codDocente'],
																									
																			)); ?>"><span class="btn-label"><i class="fa fa-fw fa-file-pdf-o"></i></span>Ver Pdf</a>
			    </tr>
			    
			    <tr id="children-<?php echo $i;?>" style="display: none;">
				    <td colspan="10">
			        	<table class="table table-striped table-bordered table-hover">
			        		<thead>
			        		<tr>
			        			<th colspan="3">Horario Principal</th>
			        			<th colspan="1">&nbsp;</th>
			        			<th colspan="5">Horario Registrado</th>	
			        		</tr>
						    <tr>			        
						        <th>Día</th>
						        <th>Hora inicial</th>
						        <th>Hora final</th>        
						        <th>&nbsp;</th>						        
						        <th>Fecha</th>
						        <th>Día</th>
						        <th>Hora inicial</th>
						        <th>Hora final</th>        
						        <th>Minutos tarde</th>      
							</tr>
						    </thead>
		        			<tbody>
		        			<?php if($curso['registro']): ?>
		        				<?php
									foreach ($curso['registro'] as $registro) :
								?>
									<tr>
										<td><?php echo $registro['codDiaSemana']; ?></td>
								        <td><?php echo $registro['horaInicioHorario']; ?></td>
								        <td><?php echo $registro['horaFinHorario']; ?></td>        
								        <td>&nbsp;</td>								        
								        <td><?php echo $registro['fecha']; ?></td>
								        <td><?php echo $registro['diaSemana']; ?></td>
								        <td><?php echo $registro['horaInicio']; ?></td>
								        <td><?php echo $registro['horaFin']; ?></td>        
								        <td><?php echo $registro['minutosTarde']; ?></td>
									</tr>
								<?php endforeach;?> 	
		        			<?php endif;?>
			        		</tbody>
			        	</table>			        
			        </td>
		        </tr>
			    <?php endforeach; ?>
			    </tbody> 
			</table>
		<?php else: ?>
			
			<h2>No se han encontrado resultados</h2>
		
		<?php endif;?>			
	</div>
</div>