<div class="box">
	<div class="box-title">
		<i class="glyphicon glyphicon-tasks"></i>
		<h3>Sílabo</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">
	
		<div class="row">
		
			<div class="col-md-12">
				<div class="col-md-3">
					<ul class="list-group">
						<li class="list-group-item">
							Código: <strong><?php echo $this->curso['codigo'];?></strong>
						</li>					
					</ul>
				</div>
				<div class="col-md-3">
					<ul class="list-group">
						<li class="list-group-item">
							Curso: <strong><?php echo $this->curso['curso'];?></strong>
						</li>
					</ul>
				</div>
				<div class="col-md-4">
					<ul class="list-group">
						<li class="list-group-item">
							Plan de Estudio: <strong><?php echo $this->curso['titulo'];?></strong>
						</li>
					</ul>
				</div>
				<div class="col-md-2">
					<ul class="list-group">
						<li class="list-group-item">
							<a class="btn btn-labeled palette-carrot btn-color" href="<?php echo $this->url("curso"); ?>"><span class="btn-label"><i class="glyphicon glyphicon-new-window"></i></span>Seleccionar curso</a>
						</li>
					</ul>
				</div>
			</div>			
			
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-7">				
									
						<div class="col-md-12">
							<div class="box">
								<div class="box-title">
									<i class="fa fa-fw fa-paper-plane"></i>
									<h3>Temáticas</h3>
								</div>
								<div class="box-body">
									
									<?php if($this->temas->count() != 0):?>
										<table class="table table-hover table-striped">
										    <thead>
										    <tr>
										    	<th>Código</th>
										        <th>Semana</th>
										        <th>Temática</th>
										        <th>Acciones</th>		        
										    </tr>
										    </thead>
										    <tbody>
										    <?php foreach ($this->temas as $tema): ?>    
										    <tr>								        
										        <td>
										        	<?php echo $this->escapeHtml($tema['codSilaboDetalle']);?>
										        </td>					        
										        
										        <td>
										        	<?php echo $this->escapeHtml($tema['semana']);?>
										        </td>
										        
										        <td>
										        	<?php echo $this->escapeHtml($tema['tematica']);?>
										        </td>		        
										        
										        <td>
													<a class="btn btn-danger btn-sm" href="<?php echo $this->url('silabo', array(
																				'action' => 'eliminar-tema',
																				'codcurso' => $this->curso['codCurso'],
																				'codsilabodetalle' => $tema['codSilaboDetalle'],
																			));?>">
														<i class="fa fa-trash-o "></i> 
													</a>
												</td>
										    </tr>
										    <?php endforeach; ?>
										    </tbody>   
										</table>
										<?php else: ?>
										
										<h2>No hay temáticas agregadas.</h2>
									
									<?php endif;?>
								
								</div>	
							</div>
						</div>
					</div>
					
					<div class="col-md-5">								
						<div class="col-md-12">
							<div class="box">
								<div class="box-title">
									<h3>Agregar Temática</h3>
								</div>
								<div class="box-body">
																	
									<?php
										$form = $this->form;
										$form->setAttribute('action', $this->url('silabo', array('action' => 'agregar-tema', 'codcurso' => $this->curso['codCurso'])));
										$form->setAttribute('class', 'form-horizontal');
										$form->prepare();
									?>

									<?php echo $this->form()->openTag($form);?>
																							
										<div class="form-group">
											<?php echo $this->formLabel($form->get('codSemana')) ?>
											<div class="col-sm-10">
												<?php echo $this->formSelect($form->get('codSemana')); ?>
												<?php echo $this->formElementErrors()
						                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
						                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
						                            ->setMessageCloseString('</div>')
						                            ->render($form->get('codSemana'));?>
											</div>
										</div>				
										
										<div class="form-group">
											<?php echo $this->formLabel($form->get('tematica')) ?>
											<div class="col-sm-10">
												<?php echo $this->formInput($form->get('tematica')); ?>
												<?php echo $this->formElementErrors()
						                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
						                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
						                            ->setMessageCloseString('</div>')
						                            ->render($form->get('tematica'));?>
											</div>
										</div>										
										
										<div class="form-group">
											<div class="col-sm-offset-2 col-sm-10">
												<?php echo $this->formInput($form->get('guardar')); ?>
											</div>
										</div>		
									
									<?php echo $this->form()->closeTag($form);?>								
								</div>	
							</div>
						</div>												
					</div>
				</div>
			</div>			
		</div>				
	</div>
</div>