<?php 
if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath().'/public'); 
} ?>

<?php echo $this->doctype(); ?>


<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GP-Syllabus'); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
            						->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        				->prependStylesheet($this->basePath('css/custom.css'))
        				->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    </head>
    <body class="login fixed">        
        <div class="wrapper animated flipInY">      
            <?php echo $this->content; ?>
        </div>
    </body>
</html>

