
<div class="logo">
	<img alt="logo Universidad Israel" src="<?php echo $this->basePath('public/img/logo_uisrael.png'); ?>"/>	
	<p style="color: #fff">GP-Syllabus <br><span style="color: #ddd">Seguimiento Académico Universitario</span></p>
	
</div>

<div class="box">
	<div class="header clearfix">
		<div class="pull-left"><i class="fa fa-sign-in"></i>Ingresar</div>
	</div>
	<?php
		$form = $this->form;
		$form->setAttribute('action', $this->url('ingresar', array('controller' => 'index', 'action' => 'index')));
		$form->prepare();
		echo $this->form()->openTag($form);
	?>
                <div class="alert alert-warning no-radius no-margin padding-sm"><i class="fa fa-info-circle"></i> Por favor inicie sesión para ingresar</div>
                <div class="box-body padding-md">
                
                	<?php echo $this->formHidden($form->get('session_token')) ?>
                
               		<?php echo $this->formHidden($form->get('csrf')) ?>
                
                    <div class="form-group">
                    	<?php //echo $this->formLabel($form->get('usuario')) ?>
                        <?php echo $this->formInput($form->get('usuario')); ?>
                        <?php echo $this->formElementErrors()
                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
                            ->setMessageCloseString('</div>')
                            ->render($form->get('usuario'));?>
                    </div>
                    <div class="form-group">
                       <?php //echo $this->formLabel($form->get('clave')) ?>
                       <?php echo $this->formInput($form->get('clave')); ?>
                       <?php echo $this->formElementErrors()
                                ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
                                ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
                                ->setMessageCloseString('</div>')
                                ->render($form->get('clave'));?>
                    </div>

						<?php
                            if ($this->messages):
                                foreach ($this->messages as $msg):
                                    ?>
                                    <div class="alert alert-error alert-dismissable bg-success">                                        
                                        <?php echo $msg; ?>
                                    </div>
                                <?php
                                endforeach;
                            endif;
                       	?> 
                    
                    	<?php
                            if ($this->errorMessages):
                                foreach ($this->errorMessages as $msg):
                                    ?>
                                    <div class="alert alert-error alert-dismissable bg-info">                                        
                                        <?php echo $msg; ?>
                                    </div>
                                <?php
                                endforeach;
                            endif;
                       	?>                      	
                       	                
                    
                    <div class="box-footer">                                                               
                        <?php echo $this->formInput($form->get('ingresar')); ?>
                    </div>

                </div>
                
	<?php echo $this->form()->closeTag($form);?>
</div>
<footer>
	<a href="<?php echo $this->url('reestablecer-clave');?>">Olvidé mi clave</a>
	<ul class="list-unstyled list-inline"></ul>
</footer>
