<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('carga-academica', array(
			'action' => $this->action,
			'codcargaacademica' => $this->cargaAcademica['codCargaAcademica'],
			'codcicloacademico' => $this->cargaAcademica['codCicloAcademico'],
			'codcurso' => $this->cargaAcademica['codCurso'],
			'codmodalidad' => $this->cargaAcademica['codModalidad'],
			'paralelo' => $this->cargaAcademica['paralelo']
	)));
	$form->setAttribute('class', 'form-horizontal');
	$form->prepare();
?>
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-title">
				<h3><?php echo $this->text; ?> Carga Académica</h3>
			</div>
			<div class="box-body padding-md">
				<?php echo $this->form()->openTag($form);?>
									
					<?php echo $this->formHidden($form->get('codCurso')); ?>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codCargaAcademica')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('codCargaAcademica')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codCargaAcademica'));?>
						</div>
					</div>					
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codigo')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('codigo')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codigo'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('curso')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('curso')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('curso'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('fechaInicioClases')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('fechaInicioClases')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('fechaInicioClases'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('esComun')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('esComun')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('esComun'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codAreaConocimiento')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codAreaConocimiento')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codAreaConocimiento'));?>
						</div>
					</div>			
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codCarreraProfesional')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codCarreraProfesional')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codCarreraProfesional'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codCicloAcademico')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codCicloAcademico')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codCicloAcademico'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codModalidad')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codModalidad')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codModalidad'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codAula')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codAula')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codAula'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codSeccion')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codSeccion')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codSeccion'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codDocente')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codDocente')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codDocente'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('paralelo')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('paralelo')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('paralelo'));?>
						</div>
					</div>
					
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<?php echo $this->formInput($form->get('guardar')); ?>
						</div>
					</div>		
				
				<?php echo $this->form()->closeTag($form);?>
			</div>
		</div>
	</div>
</div>