<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('carrera-profesional', array('action' => $this->action)));
	$form->setAttribute('class', 'form-horizontal');
	$form->prepare();
?>
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-title">
				<h3><?php echo $this->text; ?></h3>
			</div>
			<div class="box-body padding-md">
				<?php echo $this->form()->openTag($form);?>
					
					<?php echo $this->formHidden($form->get('codCarreraProfesional')); ?>
				
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codigo')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('codigo')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codigo'));?>
						</div>
					</div>
				
					<div class="form-group">
						<?php echo $this->formLabel($form->get('carreraProfesional')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('carreraProfesional')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('carreraProfesional'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codAreaConocimiento')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codAreaConocimiento')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codAreaConocimiento'));?>
						</div>
					</div>
					
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<?php echo $this->formInput($form->get('guardar')); ?>
						</div>
					</div>		
				
				<?php echo $this->form()->closeTag($form);?>
			</div>
		</div>
	</div>
</div>