<?php
	$form = $this->form;        
	$form->setAttribute('action', $this->url('carga-masiva'));
	$form->prepare();
?>

<div class="box">
	<div class="box-title">
		<h3>Seleccione archivo CSV</h3>
	</div>
	<div class="box-body">
		<?php echo $this->form()->openTag($form);?>
		
			<div class="form-group">
				<label>Nombre de tabla a cargar: </label>				
				<?php echo $this->formSelect($form->get('tabla')); ?>
				<?php echo $this->formElementErrors($form->get('tabla')); ?>		
			</div>
		
			<div class="form-group">
				<label>Agregar archivo</label>				
				<?php echo $this->formFile($form->get('csv')); ?>
				<?php echo $this->formElementErrors($form->get('csv')); ?>
				<p class="help-block">Recuerde que el nombre de la tabla y el del archivo deben coincidir.</p>			
			</div>	
			
			<?php echo $this->formhidden($form->get('csrf'));?>        
			
			<?php echo $this->formElement($form->get('submit'));?>
			
			<hr>
			<div>
				<?php if($this->errorMessage) echo $this->errorMessage;?>
			</div>
			  
		<?php echo $this->form()->closeTag(); ?>		
		
	</div>
</div>

