
<?php if($this->registros):?>
<div class="box">
	<div class="box-title">
		<h3>Registros a insertar (Verifique que los registros sean correctos y acepte)</h3>
	</div>
	<div class="box-body">
		<table class="table">
		    <thead>
		    <tr>		    	
		    	<?php foreach ($this->nombres_campos as $campo):?>		        
			        <th><?php echo $campo;?></th>
		   		<?php endforeach;?>			        
		    </tr>
		    </thead>
		    <tbody>
		    <?php foreach ($this->registros as $registro) : ?>
		    	<tr>
			    <?php foreach ($this->nombres_campos as $campo): ?>		    
		    		<td><?php echo $registro[$campo];?></td>
		    
		    	<?php endforeach; ?>
		   		</tr> 	
		    <?php endforeach; ?>
		    </tbody>
		    <tfoot>
		    <tr>
		    	<?php foreach ($this->nombres_campos as $campo):?>		        
			        <th><?php echo $campo;?></th>
		   		<?php endforeach;?>		        
		    </tr>
		    </tfoot>    
		</table>
		<hr>
		<a class="btn btn-success" href="<?php echo $this->url('carga-masiva', array('action' =>'guardar', 'file' => $this->file)); ?>">Aceptar</a>
		
	</div>
</div>	
<?php endif;?>