<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('curso', array('action' => $this->action)));
	$form->setAttribute('class', 'form-horizontal');
	$form->prepare();
?>
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-title">
				<h3><?php echo $this->text;?> Curso</h3>
			</div>
			<div class="box-body padding-md">
				<?php echo $this->form()->openTag($form);?>
					
					<?php echo $this->formHidden($form->get('codCurso')); ?>					
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codigo')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('codigo')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codigo'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('curso')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('curso')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('curso'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('nivel')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('nivel')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('nivel'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('abreviatura')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('abreviatura')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('abreviatura'));?>
						</div>
					</div>			
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('creditos')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('creditos')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('creditos'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codPlanEstudio')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codPlanEstudio')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codPlanEstudio'));?>
						</div>
					</div>
					
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<?php echo $this->formInput($form->get('guardar')); ?>
						</div>
					</div>		
				
				<?php echo $this->form()->closeTag($form);?>
			</div>
		</div>
	</div>
</div>