<?php 
	//$this->layout()->setVariable('titulo', 'Cursos');	
	//$this->layout()->setVariable('subtitulo', 'Puede visualizar sus cursos en esta ventana');
?>

<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-cube"></i>
		<h3>Mis Cursos</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">			
		
		<?php if($this->cursosDocente->count() != 0):?>
			<table class="table">
			    <thead>
			    <tr>
			        <th>Código</th>			        
			        <th>Común</th>
			        <th>Area Conocimiento</th>
			        <th>Carrera Profesional</th>
			        <th>Ciclo Académico</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Aula</th>
			        <th>Sección</th>
			        <th>Paralelo</th>
			        <th>Acciones</th>
			    </tr>
			    </thead>
			    <tbody>
			    <?php
			    	$i = 0;
					foreach ($this->cursosDocente as $curso) :
					$i++;
				?>    
			    <tr>
			        <td><?php echo $this->escapeHtml($curso['codCargaAcademica']);?></td>        
			        
			        <td><?php echo $this->escapeHtml($curso['esComun']);?></td>
			        
			        <td><?php if ($this->escapeHtml($curso['areaConocimiento'])){echo $this->escapeHtml($curso['areaConocimiento']);}else{ echo "COMUN GENERAL";}?></td>
			        
			        <td><?php if ($this->escapeHtml($curso['carreraProfesional'])){echo $this->escapeHtml($curso['carreraProfesional']);}else{ echo "COMUN GENERAL";}?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['anio'] . '-'. $curso['semestre']);?></td>    
			        
			        <td><?php echo $this->escapeHtml($curso['codigo']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['curso']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['modalidad']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['numero']);?></td>
			        
			        <td><?php echo $this->escapeHtml($curso['seccion']);?></td> 
			        
			        <td><?php echo $this->escapeHtml($curso['paralelo']);?></td>    
			        
			        <td><a class="btn btn-success" href="<?php echo $this->url('iniciar-sesion', array(
			        															'codcargaacademica'			=> $curso['codCargaAcademica'],
																        		'codcicloacademico'			=> $curso['codCicloAcademico'],
			        															'codcurso' 					=> $curso['codCurso'],
			        															'codmodalidad' 				=> $curso['codModalidad'],
			        															'paralelo' 					=> $curso['paralelo'],
			        															'codaula' 					=> $curso['codAula'],
			        															'codseccion' 				=> $curso['codSeccion']
			        												)); ?>">Iniciar clase</a></td>
			    </tr>
			    <?php endforeach; ?>
			    </tbody>
			    <tfoot>
			    <tr>
			        <th>Código</th>
			        <th>Común</th>
			        <th>Ciclo Académico</th>
			        <th>Código</th>      
			        <th>Curso</th>
			        <th>Modalidad</th>
			        <th>Aula</th>
			        <th>Sección</th>
			        <th>Paralelo</th>       
			        <th>Acciones</th>
			    </tr>
			    </tfoot>    
			</table>
			<?php else: ?>
			
			<h3>Aún no tiene cursos asignados, comuníquese con el administrador del sistema.</h3>
		
		<?php endif;?>			
	</div>
</div>

<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-info-circle"></i>
		<h3>Sesiones sin terminar</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">
	
		<?php if($this->sesionesAbiertas->count() != 0):?>
	
			<p>Para terminar una sesión abierta debe dar click en el botón <a class="btn btn-success">iniciar clase</a>, para continuar donde lo dejo.</p>
			
			<table class="table table-hover table-striped">
			    <thead>
			    <tr>
			        <th>N°</th>
			        <th>Curso</th>      
			        <th>Fecha</th>
			        <th>Hora Inicio</th>
			        <th>Registró Asistencia</th>
			        <th>Registró Avance</th>
			    </tr>
			    </thead>
			    <tbody>
			    <?php
			    	$i = 0;
					foreach ($this->sesionesAbiertas as $sesion) :
					$i++;
				?>    
			    <tr>
			        <td><?php echo $i;?></td>
			        
			        <td><?php echo $this->escapeHtml($sesion['curso']. "-" .$sesion['numero']. "-" .$sesion['seccion']) ;?></td>       
			        
			        <td><?php echo $this->escapeHtml($sesion['fecha']);?></td>
			        
			        <td><?php echo $this->escapeHtml($sesion['horaInicio']);?></td>			        
			        
			        <td>
			        	<?php if($sesion['asistenciaRealizada'] == 'Si'):?>
			        		<span class="label label-success"><?php echo $this->escapeHtml($sesion['asistenciaRealizada']);?></span>
			        	<?php else:?>
			        		<span class="label label-danger"><?php echo $this->escapeHtml($sesion['asistenciaRealizada']);?></span>
			        	<?php endif;?>
			        </td>
			        
			        <td>
			        	<?php if($sesion['avanceSilabo'] == 'Si'):?>
			        		<span class="label label-success"><?php echo $this->escapeHtml($sesion['avanceSilabo']);?></span>
			        	<?php else:?>
			        		<span class="label label-danger"><?php echo $this->escapeHtml($sesion['avanceSilabo']);?></span>
			        	<?php endif;?>
			        </td>		        		        
			        
			    </tr>
		    <?php endforeach; ?>
		    </tbody>
		    <tfoot>
			    <tr>
			        <th>N°</th>
			        <th>Nombre del curso</th>      
			        <th>Fecha</th>
			        <th>Hora Inicio</th>
			        <th>Registró Asistencia</th>
			        <th>Registró Avance</th>      
			    </tr>
		    </tfoot>    
		</table>		
		<?php else: ?>
			<p>Todos los cursos han finalizado correctamente.</p>		
		<?php endif;?>
		
	</div>
</div>