<?php 
	$this->layout()->setVariable('titulo', 'Estudiantes'); 
	//echo "<pre>";
	//var_dump($this->curso);
	//echo "</pre>";
?>

<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-group"></i>
		<h3>Listado de Estudiantes</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">
	
		<?php if($this->estudiantesMatriculados->count() != 0):?>
		<form action="<?php echo $this->url('registrar-asistencia');?>" method="post">		
			
			<input type="hidden" name="codSesionClase" value="<?php echo $this->dataUrl[0]; ?>">
			<input type="hidden" name="codCargaAcademica" value="<?php echo $this->dataUrl[1]; ?>"/>
			<input type="hidden" name="codCicloAcademico" value="<?php echo $this->dataUrl[2]; ?>"/>
			<input type="hidden" name="codCurso" value="<?php echo $this->dataUrl[3]; ?>"/>
			<input type="hidden" name="codModalidad" value="<?php echo $this->dataUrl[4]; ?>"/>
			<input type="hidden" name="paralelo" value="<?php echo $this->dataUrl[5]; ?>"/>
			<input type="hidden" name="codAula" value="<?php echo $this->dataUrl[6]; ?>"/>
			<input type="hidden" name="codSeccion" value="<?php echo $this->dataUrl[7]; ?>"/>
			
			<table class="table table-hover table-striped">
			    <thead>
			    <tr>
			        <th>N°</th>
			        <th>Foto</th>
			        <th>Código</th>  
			        <th>Apellidos</th>
			        <th>Nombres</th>
			        <th>Correo</th>
			        <th>Acciones</th>
			    </tr>
			    </thead>
			    <tbody>
			    
			    <?php
			    	$i = 0;
					foreach ($this->estudiantesMatriculados as $estudiante) :
					$i++;
				?>    
			    <tr>
			        <td><?php echo $i;?></td>
			        
			        <td><div class="avatar"><img src="<?php echo $this->basePath('img/avatar4.jpg');?>" alt="imagen de estudiante" style="box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.3); height: 48px; width: 48px;"/></div></td>       
			        
			        <td><?php echo $this->escapeHtml($estudiante['codEstudiante']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['primerApellido'] . ' ' . $estudiante['segundoApellido']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['nombres']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['correo']);?></td>
			        
			        <td>			        	
			        	<label><input type="radio" name="<?php echo $this->escapeHtml($estudiante['codEstudiante']);?>" value="Puntual"/>Puntual &nbsp</label>
			        	<label><input type="radio" name="<?php echo $this->escapeHtml($estudiante['codEstudiante']);?>" value="Tarde" />Tarde &nbsp</label>
			        	<label><input type="radio" name="<?php echo $this->escapeHtml($estudiante['codEstudiante']);?>" value="Falta" checked="checked" />Falta</label>
			        </td>
			        
			    </tr>
			    <?php endforeach; ?>
			    </tbody>
			    <tfoot>
			    <tr>
			        <th>N°</th>
			        <th>Foto</th>
			        <th>Código</th>      
			        <th>Apellidos</th>
			        <th>Nombres</th>
			        <th>Correo</th>
			        <th>Acciones</th>
			    </tr>
			    </tfoot>    
			</table>
			<hr>
			<input class="btn btn-success btn-outline" type="submit" value="Registrar asistencia"/>
		</form>
		
		<?php else: ?>

			<h3>Aún no tiene alumnos matriculados en su curso: <?php echo $this->cargaAcademica['curso'];?></h3>
			<p>Comuníquese con el administrador del sistema.</p>
		
		<?php endif;?>
			
	</div>
</div>


