<div class="row">

	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-sun-flower">
			<h4>Usuarios</h4>
			<p><a href="<?php echo $this->url("usuario"); ?>">Ver</a></p>			
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<p><a href="<?php echo $this->url("usuario");?>">&nbsp;</a></p>
			<i class="glyphicon glyphicon-user"></i>
		</div>
	</div>
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-wet-asphalt">
			<h4>Administrador</h4>
			<p><a href="<?php echo $this->url("administrador"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("administrador",array('action'=>'agregar-administrador'));?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-child"></i>
		</div>
	</div>	
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-peter-river">
			<h4>Docente</h4>
			<p><a href="<?php echo $this->url("docente"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("docente", array('action' => 'agregar-docente')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-male"></i>
		</div>
	</div>
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-nephritis">
			<h4>Estudiante</h4>
			<p><a href="<?php echo $this->url("estudiante"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("estudiante", array('action' => 'agregar-estudiante')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-group"></i>
		</div>
	</div>	
</div>

<div class="row">
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-green-sea">
			<h4>Area de Conocimiento</h4>
			<p><a href="<?php echo $this->url("area-conocimiento"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("area-conocimiento", array('action' => 'agregar-area-conocimiento')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-institution"></i>
		</div>
	</div>
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-alizarin">
			<h4>Carrera Profesional</h4>
			<p><a href="<?php echo $this->url("carrera-profesional"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("carrera-profesional", array('action' => 'agregar-carrera-profesional')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-graduation-cap"></i>
		</div>
	</div>
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-emerald">
			<h4>Ciclo Académico</h4>
			<p><a href="<?php echo $this->url("ciclo-academico"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("ciclo-academico", array('action' => 'agregar-ciclo')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-ellipsis-h"></i>
		</div>
	</div>

	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-amethyst">
			<h4>Plan de Estudio</h4>
			<p><a href="<?php echo $this->url("plan-estudio"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("plan-estudio", array('action' => 'agregar-plan')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-file-text"></i>
		</div>
	</div>	
</div>

<div class="row">	
	
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-carrot">
			<h4>Curso</h4>
			<p><a href="<?php echo $this->url("curso", array('action' => 'index')); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("curso", array('action' => 'agregar-curso')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-cube"></i>
		</div>
	</div>
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-green-sea">
			<h4>Sílabo</h4>
			<p><a href="<?php echo $this->url("silabo"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("silabo", array('action' => 'agregar-silabo')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-book"></i>
		</div>
	</div>	
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-concrete">
			<h4>Carga Académica</h4>
			<p><a href="<?php echo $this->url("carga-academica"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("carga-academica", array('action' => 'agregar-carga-academica')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="glyphicon glyphicon-new-window"></i>
		</div>
	</div>	
	<div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
		<div class="custom-box palette-midnight-blue">
			<h4>Aula</h4>
			<p><a href="<?php echo $this->url("aula"); ?>">Ver</a></p>
			<p><a href="<?php echo $this->url("aula", array('action' => 'agregar-aula')); ?>">Agregar</a></p>
			<p><a href="<?php echo $this->url("carga-masiva"); ?>">Carga masiva</a></p>
			<i class="fa fa-fw fa-institution"></i>
		</div>
	</div>
</div>

<div class="row">
	
</div>








