<?php

 $title = 'Eliminar Plan de Estudio';
 $this->headTitle($title);

 ?>

 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <h3>Esta seguro que desea eliminar el Plan de Estudio: <strong><?php echo $this->escapeHtml($this->planEstudio['titulo']);?></strong></h3>
 
 <p>La eliminación es definitiva e irreversible</p>
 
 <form action="<?php echo $this->url('plan-estudio', array('action' => 'eliminar-plan')); ?>" method="post">

	 <input type="hidden" name="codPlanEstudio" value="<?php echo (int) $this->planEstudio['codPlanEstudio']; ?>" />
	 <input type="submit" name="eliminar" value="si" />
	 <input type="submit" name="eliminar" value="no" />

 </form>