<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('estudiante', array('action' => $this->action)));
	$form->setAttribute('class', 'form-horizontal');
	$form->prepare();
?>
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-title">
				<h3><?php echo $this->text ?> Estudiante</h3>
			</div>
			<div class="box-body padding-md">
				<?php echo $this->form()->openTag($form);?>
					
					<?php echo $this->formHidden($form->get('codEstudiante')); ?>
					
					<?php echo $this->formHidden($form->get('Persona')->get('codPersona')); ?>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('anioIngreso')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('anioIngreso')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('anioIngreso'));?>
						</div>
					</div>			
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('codCarreraProfesional')) ?>
						<div class="col-sm-10">
							<?php echo $this->formSelect($form->get('codCarreraProfesional')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('codCarreraProfesional'));?>
						</div>
					</div>
				
					<div class="form-group">
						<?php echo $this->formLabel($form->get('Persona')->get('nombres')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('Persona')->get('nombres')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('Persona')->get('nombres'));?>
						</div>
					</div>
				
					<div class="form-group">
						<?php echo $this->formLabel($form->get('Persona')->get('primerApellido')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('Persona')->get('primerApellido')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('Persona')->get('primerApellido'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('Persona')->get('segundoApellido')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('Persona')->get('segundoApellido')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('Persona')->get('segundoApellido'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('Persona')->get('tipoDocumento')) ?>
						<div class="col-sm-10">
							<?php echo $this->formRadio($form->get('Persona')->get('tipoDocumento')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('Persona')->get('tipoDocumento'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('Persona')->get('numeroDocumento')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('Persona')->get('numeroDocumento')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('Persona')->get('numeroDocumento'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('Persona')->get('fechaNacimiento')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('Persona')->get('fechaNacimiento')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('Persona')->get('fechaNacimiento'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('Persona')->get('correo')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('Persona')->get('correo')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('Persona')->get('correo'));?>
						</div>
					</div>
					
					<div class="form-group">
						<?php echo $this->formLabel($form->get('Persona')->get('celular')) ?>
						<div class="col-sm-10">
							<?php echo $this->formInput($form->get('Persona')->get('celular')); ?>
							<?php echo $this->formElementErrors()
	                            ->setMessageOpenFormat('<div class="alert alert-error alert-dismissable">')
	                            ->setMessageSeparatorString('</div><div class="alert alert-error alert-dismissable">')
	                            ->setMessageCloseString('</div>')
	                            ->render($form->get('Persona')->get('celular'));?>
						</div>
					</div>
					
					<div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
							<?php echo $this->formInput($form->get('guardar')); ?>
						</div>
					</div>		
				
				<?php echo $this->form()->closeTag($form);?>
			</div>
		</div>
	</div>
</div>