<?php $url_order = ($this->order == 'ASC') ? 'DESC' : 'ASC'; ?>

<?php
	$buscarForm = $this->buscarForm;
	$buscarForm->setAttribute('action', $this->url('estudiante'));
	$buscarForm->prepare();
?>

<div class="box">
	<div class="box-title">
		<i class="fa fa-fw fa-group"></i>
		<h3>Estudiantes</h3>
		<div class="pull-right box-toolbar">
			<a class="btn btn-link btn-xs collapse-box" href="#"><i class="fa fa-chevron-up"></i></a>			
		</div>
	</div>
	<div class="box-body">
	
		<div class="row">
		
			<div class="col-md-6">
				<a class="btn btn-labeled btn-success" href="<?php echo $this->url("estudiante", array('action' => 'agregar-estudiante')); ?>"><span class="btn-label"><i class="fa fa-fw fa-plus-square"></i></span>Agregar</a>
			</div>
			
			<div class="col-lg-6 col-md-6 col-sm-8 col-xs-12 margin-bottom">
				<?php echo $this->form()->openTag($buscarForm);?>
					<div class="input-group">						
						<?php echo $this->formInput($buscarForm->get('texto')); ?>
						<span class="input-group-btn">
							<?php echo $this->formInput($buscarForm->get('buscar')); ?>
						</span>
					</div>
				<?php echo $this->form()->closeTag($buscarForm);?>
			</div>
			
		</div>
		
		<hr>
		
		<?php if($this->estudiantes->count() != 0):?>
			<table class="table table-hover table-striped" data-server="es">
			    <thead>
			    <tr>
			        <th><a href="<?php echo $this->url('estudiante', array('action' => 'index', 'orderby' => 'codestudiante', 'order' => $url_order)); ?>">Código<?php if ($this->orderby == 'carreraprofesional'): ?><i class="glyphicon glyphicon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
			        <th>Año</th>
			        <th><a href="<?php echo $this->url('estudiante', array('orderby' => 'nombres', 'order' => $url_order)); ?>">Nombres</a></th>
			        <th><a href="<?php echo $this->url('estudiante', array('action' => 'index', 'orderby' => 'primerApellido', 'order' => $url_order)); ?>">Primer apellido<?php if ($this->orderby == 'carreraprofesional'): ?><i class="glyphicon glyphicon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>      
			        <th><a href="<?php echo $this->url('estudiante', array('action' => 'index', 'orderby' => 'segundoApellido', 'order' => $url_order)); ?>">Segundo apellido<?php if ($this->orderby == 'carreraprofesional'): ?><i class="glyphicon glyphicon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>
			        <th>Tipo de documento</th>
			        <th><a href="<?php echo $this->url('estudiante', array('action' => 'index', 'orderby' => 'numeroDocumento', 'order' => $url_order)); ?>">Número de documento<?php if ($this->orderby == 'carreraprofesional'): ?><i class="glyphicon glyphicon-chevron-<?php echo $url_order == 'ASC' ? 'down' : 'up' ?>"></i><?php endif; ?></a></th>      
			        <th>Correo</th>
			        <th>Celular</th>
			        <th>Carrera Profesional</th>
			        <th>Acciones</th>			        
			    </tr>
			    </thead>
			    <tbody>
			    <?php foreach ($this->estudiantes as $estudiante): ?>    
			    <tr>     
			        
			        <td><?php echo $this->escapeHtml($estudiante['codEstudiante']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['anioIngreso']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['nombres']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['primerApellido']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['segundoApellido']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['tipoDocumento']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['numeroDocumento']);?></td>
			        
			        <td><?php echo $this->escapeHtml($estudiante['correo']);?></td>	
			        
			        <td><?php echo $this->escapeHtml($estudiante['celular']);?></td>	
			        
			        <td><?php echo $this->escapeHtml($estudiante['carreraProfesional']);?></td>
			        
			        <td>
						<a title="Editar estudiante" class="btn btn-info btn-sm" href="<?php echo $this->url('estudiante', array('action' => 'editar-estudiante', 'codestudiante' =>$estudiante['codEstudiante']));?>">
							<i class="fa fa-edit "></i>  
						</a>
						<a title="Eliminar estudiante" class="btn btn-danger btn-sm delete-this" id="delete-<?php echo $this->escapeHtml($estudiante['codEstudiante']);?>" href="<?php echo $this->url('estudiante', array('action' => 'eliminar-estudiante', 'codestudiante' =>$estudiante['codEstudiante']));?>">
							<i class="fa fa-trash-o"></i> 
						</a>
					</td>
			    </tr>
			    <?php endforeach; ?>
			    </tbody>
			    <tfoot>
			    <tr>
			        <th>Código</th>
			        <th>Año</th>
			        <th>Nombres</th>
			        <th>Primer apellido</th>      
			        <th>Segundo apellido</th>
			        <th>Tipo de documento</th>
			        <th>Número de documento</th>      
			        <th>Correo</th>
			        <th>Celular</th>
			        <th>Carrera Profesional</th>
			        <th>Acciones</th>
			    </tr>
			    </tfoot>    
			</table>


			<?php echo $this->paginationControl($this->estudiantes, 'Sliding', 'paginator', array('route' => 'estudiante', 'action' => 'index', 'orderby' => $this->orderby, 'order' => $order));?>


			<?php else: ?>
			
			<h2>No se han encontrado resultados.</h2>
		
		<?php endif;?>			
	</div>
</div>
